### ISSUE TITLE
Implement pandas ExtensionArray tests for AwkwardArray

### ISSUE THREAD

**Issue by mroeschke** [intake/akimbo#3]
Here's a small doc reference on how to implement the tests: https://pandas.pydata.org/docs/dev/development/extending.html#testing-extension-arrays

All the tests would be located here: https://github.com/pandas-dev/pandas/tree/main/pandas/tests/extension/base

It covers a good amount of the pandas API surface area, and should ensure most operations with `AwkardArray` are compatable with the API. Happy to receive feedback if the tests are not well defined in a certain area!

cc @martindurant @douglasdavis

**Comment by douglasdavis** [comment]
Great thanks for pointing those out :+1:

**Comment by douglasdavis** [comment]
One PR in but leaving this open until we cover more of the surface area
